# Generated by Django 4.2.6 on 2024-04-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='date_created',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
    ]
