# Generated by Django 4.2.6 on 2024-04-24 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.TextField(),
        ),
    ]
