# Generated by Django 4.2.6 on 2024-04-30 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_salestransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuantityAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.IntegerField()),
                ('quantity_removed', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_adjustments', to='inventory.inventoryitem')),
            ],
        ),
    ]
