# Generated by Django 4.2.6 on 2024-04-30 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='quantity_sold',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='total_quantity_sold',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions', to='inventory.inventoryitem'),
        ),
    ]
