# Generated by Django 4.2.6 on 2024-05-01 06:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryitemlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitemlog',
            name='action',
            field=models.CharField(choices=[('update', 'Update'), ('issue', 'Issue')], max_length=10),
        ),
        migrations.AlterField(
            model_name='inventoryitemlog',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
