# Generated by Django 4.2.6 on 2024-05-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_inventoryitemlog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='is_available_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='InventoryItemLog',
        ),
    ]
