# Generated by Django 4.2.6 on 2024-05-01 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_inventoryitem_is_available_for_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='sale_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
