# Generated by Django 4.2.6 on 2024-05-02 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_salestransaction_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestransaction',
            old_name='sale_price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='is_available_for_sale',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='total_quantity_sold',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='sale_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
