# Generated by Django 4.2.6 on 2024-05-03 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_salesrecord_salesrecorditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='salesrecorditem',
            name='sales_record',
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
        migrations.DeleteModel(
            name='SalesRecordItem',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.customer'),
        ),
    ]
