# Generated by Django 4.2.6 on 2024-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_customer_remove_salesrecorditem_sales_record_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='customer',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='customer_name',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='mobile_number',
            field=models.CharField(default=100, max_length=20),
            preserve_default=False,
        ),
    ]
