# Generated by Django 4.2.6 on 2024-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_remove_salestransaction_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
