# Generated by Django 4.2.6 on 2024-05-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_salestransaction_unit_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='items',
            field=models.ManyToManyField(related_name='sales_transactions', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='quantity_sold',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='SoldItem',
        ),
    ]
