# Generated by Django 4.2.6 on 2024-05-04 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_alter_salestransaction_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='address',
            field=models.CharField(default=42, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='items_sold',
            field=models.ManyToManyField(blank=True, related_name='sales_transactions_sold', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_transactions_as_item_id', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='sales_transactions_as_items', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='SalesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField()),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem')),
                ('sales_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.salestransaction')),
            ],
        ),
    ]
