# Generated by Django 4.2.6 on 2024-05-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_salesrecord_salesrecorditem_remove_cartitem_cart_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salestransaction',
            name='address',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='gst_amount',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='items',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='items_sold',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='total_price_with_gst',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='inventory_item',
            field=models.ForeignKey(default=42, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='sale_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
