# Generated by Django 4.2.6 on 2024-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_alter_salestransaction_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
