# Generated by Django 4.2.6 on 2024-05-08 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_userprofile_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_number',
        ),
    ]
