# Generated by Django 4.2.6 on 2024-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0035_supplier_boughtitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boughtitem',
            name='total_price_gst',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
