# Generated by Django 4.2.6 on 2024-05-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0036_boughtitem_total_price_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boughtitem',
            name='bought_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='boughtitem',
            name='total_price_gst',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
